### ISSUE TITLE
Request: Extension name (`Sspmp`) in the document

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-spmp#3]
<https://wiki.riscv.org/display/HOME/Specification+Status>
mentions `Sspmp` as the SPMP extension and I want this to be clarified.

Specifically, I request that the extension name (`Sspmp`) is mentioned *inside* the specification.

Note:
We currently have this name `Sspmp` in [`header.adoc`](https://github.com/riscv/riscv-spmp/blame/887b9853638fbc418813ebbe9aa445fdc6c916a5/header.adoc#L2) but this is not displayed.  I could not find this name in the metadata either.

**Comment by Ddnirvana** [comment]
Close out-dated issue.
